version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - php

  php:
    # image: php:7-fpm
    build: ./php
    volumes:
      - ./src:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    stdin_open: true # ←を追加
    depends_on:
      - db

  db:
    image: mysql:latest
    ports:
      - 13306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.conf:/etc/mysql/conf.d
      - ./mysql/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: quizy
      MYSQL_USER: asaka
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: secret

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8888:80
    depends_on:
      - db